// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Unisat Wallet Connect', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit()
  })
  it('Unisat Wallet Connect', async function () {
    await driver.get('http://localhost:5173/')
    await driver.manage().window().setRect({ width: 1379, height: 1020 })
    {
      const element = await driver.findElement(By.css('.connect-bitcoin'))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css('.connect-bitcoin')).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, 'body')
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id('connect-l1')).click()
    assert(await driver.switchTo().alert().getText() == 'Which wallet would you like to connect? 1 - Unisat, 2 - Xverse')
    {
      const alert = await driver.switchTo().alert()
      await alert.sendKeys('1')
      await alert.accept()
    }
    await driver.findElement(By.css('.simulate-l1')).click()
  })
})
