# This file has been generated by node2nix 1.11.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "bignumber.js-git+ssh://git@github.com/frozeman/bignumber.js-nolookahead.git#57692b3ecfc98bbdd6b3a516cb2353652ea49934" = {
      name = "bignumber.js";
      packageName = "bignumber.js";
      version = "2.0.7";
      src = fetchgit {
        url = "ssh://git@github.com/frozeman/bignumber.js-nolookahead.git";
        rev = "57692b3ecfc98bbdd6b3a516cb2353652ea49934";
        sha256 = "3b0aa78d5f77fc72122505c8e6e5842abfb931364571f6f4b1e8318b1cfe4c6a";
      };
    };
    "cookiejar-2.1.3" = {
      name = "cookiejar";
      packageName = "cookiejar";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookiejar/-/cookiejar-2.1.3.tgz";
        sha512 = "JxbCBUdrfr6AQjOXrxoTvAMJO4HBTUIlBzslcJPAz+/KT8yk53fXun51u+RenNYvad/+Vc2DIz5o9UxlCDymFQ==";
      };
    };
    "crypto-js-3.3.0" = {
      name = "crypto-js";
      packageName = "crypto-js";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-js/-/crypto-js-3.3.0.tgz";
        sha512 = "DIT51nX0dCfKltpRiXV+/TVZq+Qq2NgF4644+K7Ttnla7zEzqc+kjJyiB96BHNyUTBxyjzRcZYpUdZa+QAqi6Q==";
      };
    };
    "utf8-2.1.2" = {
      name = "utf8";
      packageName = "utf8";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf8/-/utf8-2.1.2.tgz";
        sha512 = "QXo+O/QkLP/x1nyi54uQiG0XrODxdysuQvE5dtVqv7F5K2Qb6FsN+qbr6KhF5wQ20tfcV3VQp0/2x1e1MRSPWg==";
      };
    };
    "web3-legacy-git+ssh://git@github.com/melnx/web3.js.git#5f91ec3801d6d3a0a1e22410ddc2ad0166d9190f" = {
      name = "web3";
      packageName = "web3";
      version = "0.20.7";
      src = fetchgit {
        url = "ssh://git@github.com/melnx/web3.js.git";
        rev = "5f91ec3801d6d3a0a1e22410ddc2ad0166d9190f";
        sha256 = "07e6bb6179c0be1c83c302b260b763a6f7ab399f5f8231774704ea4eb9041c5b";
      };
    };
    "xhr2-cookies-1.1.0" = {
      name = "xhr2-cookies";
      packageName = "xhr2-cookies";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xhr2-cookies/-/xhr2-cookies-1.1.0.tgz";
        sha512 = "hjXUA6q+jl/bd8ADHcVfFsSPIf+tyLIjuO9TwJC9WI6JP2zKcS7C+p56I9kCLLsaCiNT035iYvEUUzdEFj/8+g==";
      };
    };
    "xmlhttprequest-1.8.0" = {
      name = "xmlhttprequest";
      packageName = "xmlhttprequest";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlhttprequest/-/xmlhttprequest-1.8.0.tgz";
        sha512 = "58Im/U0mlVBLM38NdZjHyhuMtCqa61469k2YP/AaPbvCoV9aQGUpbJBj1QRm2ytRiVQBD/fsw7L2bJGDVQswBA==";
      };
    };
  };
  args = {
    name = "_at_portal_slash_portal";
    packageName = "@portal/portal";
    version = "0.0.0";
    src = ./..;
    dependencies = [
      sources."cookiejar-2.1.3"
      sources."crypto-js-3.3.0"
      (sources."web3-legacy-git+ssh://git@github.com/melnx/web3.js.git#5f91ec3801d6d3a0a1e22410ddc2ad0166d9190f" // {
        dependencies = [
          sources."bignumber.js-git+ssh://git@github.com/frozeman/bignumber.js-nolookahead.git#57692b3ecfc98bbdd6b3a516cb2353652ea49934"
          sources."utf8-2.1.2"
        ];
      })
      sources."xhr2-cookies-1.1.0"
      sources."xmlhttprequest-1.8.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The Portal server";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
