= Polar Setup

== Docker

Polar requires Docker and Docker Compose. One way to satisfy this requirement (for Linux) is to install Docker Engine using the instructions on the following two pages

- https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository[install using the repository]
- https://docs.docker.com/engine/install/linux-postinstall/[post-installation steps]

Manage Docker as a non-root user and set it up to start as a service on boot

== Polar

Download https://lightningpolar.com/[Polar]

Make sure the downloaded AppImage file is executable

[source, bash]
----
docker login
./polar-linux-x86_64-v1.4.0.AppImage
----
Polar should register both Docker and Docker Compose and offer to create a new Lightning network

== Create Networks and Nodes

=== Create Lightning Network 1
Use 3 LND nodes and 1 Bitcoin node

Start them up

The 3 LND nodes will automatically be named Alice, Bob, and Carol. Add funds to all three. Mine. Click on Alice and create an incoming channel from Bob. Click on Carol and create an outgoing channel to Bob.

=== Create Lightning Network 2
Do the same, except have the two channels run in the opposite direction from Alice to Bob and Bob to Carol.

=== Note Settings for Alice and Carol
Click on Alice's and Carol's nodes. Select *Connect* and note where the following settings are

- GRPC Host
- TLS Cert (HEX)
- Admin Macaroon (HEX)
- Invoice Macaroon (HEX)

When copying over the GRPC Host later, replace 127.0.0.1 with localhost in the GRPC host URL